global:
  scrape_interval: 15s
  external_labels:
    monitor: codelab-monitor
  
scrape_configs:
#local_prometheus
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'localhost:9090'   
#application_metrics
  # - job_name: application
  #   scrape_interval: 15s
  #   metrics_path: /application/actuator/prometheus
  #   static_configs:
  #     - targets:
  #         - 'IP'
#container-metrics
  - job_name: container-metrics
    scrape_interval: 5s
    static_configs:
    - targets:
      - 10.0.8.137:9101
    
  - job_name: container-metrics-s
    scrape_interval: 5s
    static_configs:
    - targets:
      - 10.0.8.175:9101
#server-metrics
  - job_name: node-metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.0.8.137:9100

  - job_name: node-metrics-s
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.0.8.175:9100
